### ISSUE TITLE
RunVoicemeeter() don't start/open Voicemeeter

### ISSUE THREAD

**Issue by A-tG** [A-tG/Voicemeeter-Remote-API-dll-dynamic-wrapper#1]
VBVMR_RunVoicemeeter always return -1 (not installed). Might be the problem with the dll itself.

**Comment by A-tG** [comment]
Temporary solution: build your project in x86 so the 32bit version of DLL will be used.

**Comment by onyx-and-iris** [comment]
I have had this same problem myself. Run simply fails to start VB, I've been using the 64bit dll.

**Comment by A-tG** [comment]
Should be fixed in 3.0.1.7+ version
